version: "3.7"
services:
    db:
        image: vvmk/ssr-db
        ports:
            - "5432:5432"
        env_file:
            - ./scratch/db-vars.env
        volumes:
            - db-data:/var/lib/postgresql/data
        networks:
            - ssr-net
        deploy:
            placement:
                constraints: [node.role == manager]

    shineserver:
        image: vvmk/ssr-shineserver
        ports:
            - "8001:8001"
        networks:
            - ssr-net
        depends_on: 
            - db
        env_file:
            - ./scratch/shineserver-vars.env

    web:
        image: vvmk/ssr
        ports:
            - "80:80"
        networks:
            - ssr-net

networks:
    ssr-net: 
        driver: overlay

volumes:
    db-data:
